apiVersion: v1
kind: ServiceAccount
metadata:
  name: attendee-sa
  namespace: attendee
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::248127682412:role/meeting-assistant-eks-attendee-attendee-sa-role
